/* eslint-disable import/no-cycle */
/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = 'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* PLINE APP */
export const PLINE_GET_LIST = 'PLINE_GET_LIST';
export const PLINE_GET_LIST_SUCCESS = 'PLINE_GET_LIST_SUCCESS';
export const PLINE_GET_LIST_ERROR = 'PLINE_GET_LIST_ERROR';
export const PLINE_GET_LIST_WITH_FILTER = 'PLINE_GET_LIST_WITH_FILTER';
export const PLINE_CHANGE_LIST_ORDER = 'PLINE_CHANGE_LIST_ORDER';
export const PLINE_GET_LIST_WITH_ORDER = 'PLINE_GET_LIST_WITH_ORDER';
export const PLINE_GET_LIST_SEARCH = 'PLINE_GET_LIST_SEARCH';
export const PLINE_SELECTED_ITEMS_CHANGE = 'PLINE_SELECTED_ITEMS_CHANGE';
export const PLINE_DELETE = 'PLINE_DELETE';
export const PLINE_DELETE_SUCCESS = 'PLINE_DELETE_SUCCESS';
export const PLINE_DELETE_ERROR = 'PLINE_DELETE_ERROR';
export const PLINE_GET_DETAILS = 'PLINE_GET_DETAILS';
export const PLINE_GET_DETAILS_SUCCESS = 'PLINE_GET_DETAILS_SUCCESS';
export const PLINE_GET_DETAILS_ERROR = 'PLINE_GET_DETAILS_ERROR';
export const STEP_GET_LIST_BY_PLINE = 'STEP_GET_LIST_BY_PLINE';
export const STEP_GET_LIST_BY_PLINE_SUCCESS = 'STEP_GET_LIST_BY_PLINE_SUCCESS';
export const STEP_GET_LIST_BY_PLINE_ERROR = 'STEP_GET_LIST_BY_PLINE_ERROR';

/* REPORTS APP */
export const REPORT_GET_LIST = 'REPORT_GET_LIST';
export const REPORT_GET_LIST_SUCCESS = 'REPORT_GET_LIST_SUCCESS';
export const REPORT_GET_LIST_ERROR = 'REPORT_GET_LIST_ERROR';
export const REPORT_GET_LIST_WITH_FILTER = 'REPORT_GET_LIST_WITH_FILTER';
export const REPORT_CHANGE_LIST_ORDER = 'REPORT_CHANGE_LIST_ORDER';
export const REPORT_GET_LIST_WITH_ORDER = 'REPORT_GET_LIST_WITH_ORDER';
export const REPORT_GET_LIST_SEARCH = 'REPORT_GET_LIST_SEARCH';
export const REPORT_SELECTED_ITEMS_CHANGE = 'REPORT_SELECTED_ITEMS_CHANGE';
export const REPORT_DELETE = 'REPORT_DELETE';
export const REPORT_DELETE_SUCCESS = 'REPORT_DELETE_SUCCESS';
export const REPORT_DELETE_ERROR = 'REPORT_DELETE_ERROR';
export const PLINE_STATUS_GET_LIST = 'PLINE_STATUS_GET_LIST';
export const PLINE_STATUS_GET_LIST_SUCCESS = 'PLINE_STATUS_GET_LIST_SUCCESS';
export const PLINE_STATUS_GET_LIST_ERROR = 'PLINE_STATUS_GET_LIST_ERROR';
export const REPORT_METRIC_GET_LIST = 'REPORT_METRIC_GET_LIST';
export const REPORT_METRIC_GET_LIST_SUCCESS = 'REPORT_METRIC_GET_LIST_SUCCESS';
export const REPORT_METRIC_GET_LIST_ERROR = 'REPORT_METRIC_GET_LIST_ERROR';
export const REPORT_GET_LIST_BY_PLINE = 'REPORT_GET_LIST_BY_PLINE';
export const REPORT_GET_LIST_BY_PLINE_SUCCESS = 'REPORT_GET_LIST_BY_PLINE_SUCCESS';
export const REPORT_GET_LIST_BY_PLINE_ERROR = 'REPORT_GET_LIST_BY_PLINE_ERROR';
export const REPORT_METRIC_GET_LIST_BY_PLINE = 'REPORT_METRIC_GET_LIST_BY_PLINE';
export const REPORT_METRIC_GET_LIST_BY_PLINE_SUCCESS = 'REPORT_METRIC_GET_LIST_BY_PLINE_SUCCESS';
export const REPORT_METRIC_GET_LIST_BY_PLINE_ERROR = 'REPORT_METRIC_GET_LIST_BY_PLINE_ERROR';
export const PLINE_STATUS_GET_LIST_BY_PLINE = 'PLINE_STATUS_GET_LIST_BY_PLINE';
export const PLINE_STATUS_GET_LIST_BY_PLINE_SUCCESS = 'PLINE_STATUS_GET_LIST_BY_PLINE_SUCCESS';
export const PLINE_STATUS_GET_LIST_BY_PLINE_ERROR = 'PLINE_STATUS_GET_LIST_BY_PLINE_ERROR';
export const REPORT_GET_DETAILS = 'REPORT_GET_DETAILS';
export const REPORT_GET_DETAILS_SUCCESS = 'REPORT_GET_DETAILS_SUCCESS';
export const REPORT_GET_DETAILS_ERROR = 'REPORT_GET_DETAILS_ERROR';
export const REPORT_METRIC_GET_LIST_BY_REPORT = 'REPORT_METRIC_GET_LIST_BY_REPORT';
export const REPORT_METRIC_GET_LIST_BY_REPORT_SUCCESS = 'REPORT_METRIC_GET_LIST_BY_REPORT_SUCCESS';
export const REPORT_METRIC_GET_LIST_BY_REPORT_ERROR = 'REPORT_METRIC_GET_LIST_BY_REPORT_ERROR';

/* ALGORITHM APP */
export const ALGORITHM_GET_LIST = 'ALGORITHM_GET_LIST';
export const ALGORITHM_GET_LIST_SUCCESS = 'ALGORITHM_GET_LIST_SUCCESS';
export const ALGORITHM_GET_LIST_ERROR = 'ALGORITHM_GET_LIST_ERROR';
export const ALGORITHM_GET_LIST_WITH_FILTER = 'ALGORITHM_GET_LIST_WITH_FILTER';
export const ALGORITHM_CHANGE_LIST_ORDER = 'ALGORITHM_CHANGE_LIST_ORDER';
export const ALGORITHM_GET_LIST_WITH_ORDER = 'ALGORITHM_GET_LIST_WITH_ORDER';
export const ALGORITHM_GET_LIST_SEARCH = 'ALGORITHM_GET_LIST_SEARCH';
export const ALGORITHM_SELECTED_ITEMS_CHANGE = 'ALGORITHM_SELECTED_ITEMS_CHANGE';
export const ALGORITHM_GET_DETAILS = 'ALGORITHM_GET_DETAILS';
export const ALGORITHM_GET_DETAILS_SUCCESS = 'ALGORITHM_GET_DETAILS_SUCCESS';
export const ALGORITHM_GET_DETAILS_ERROR = 'ALGORITHM_GET_DETAILS_ERROR';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
export * from './pline/actions';
export * from './reports/actions';
export * from './algorithm/actions';
